### ISSUE TITLE
This hello world fails to compile

### ISSUE THREAD

**Issue by rdebath** [Cole320/Brainfuck-Transpiler#1]
And you thought you knew how bad it was :grin: 
```
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by xnicoleisaloser** [comment]
Haha sorry for the "undefined behavior", forgot to add "pass" to a while loop if it's empty.
I appreciate the bug report.
